### ISSUE TITLE
Deploy to Github did not work

### ISSUE THREAD

**Issue by Jide-Muritala** [4GeeksAcademy/react-hello#75]
I just completed the Simple counter with React exercise and it worked properly on the server:
![Screenshot 2023-06-12 at 10 01 30 PM](https://github.com/4GeeksAcademy/react-hello/assets/115728688/523a16f1-333b-446a-9f7a-2dd76c225b46)

When I deployed to Github, it deployed successfully in the terminal:
![Screenshot 2023-06-12 at 9 59 21 PM](https://github.com/4GeeksAcademy/react-hello/assets/115728688/c0d950ee-4508-4d28-8c7d-cc47be38180a)

However, it does not show anything on the Github-pages link where it deployed:
![Screenshot 2023-06-12 at 10 01 09 PM](https://github.com/4GeeksAcademy/react-hello/assets/115728688/70f0967d-1aa1-438d-b099-e7022dcce26d)

**Comment by rick-rodriguez16** [comment]
I would recommend using vercel.  Its just a matter of linking to your Github account, adding a new project by selecting from the repos vercel finds in your Github account, and clicking deploy.  Zero configuration.  Super easy.  Good luck.

**Comment by Jide-Muritala** [comment]
Thank you very much!
